=== jpaoletti/jPOS-Presentation-Manager/modules/pm_core/cfg/entity.dtd
<!ENTITY % xhtml1-lat1 SYSTEM "xhtml1-lat1.ent">  %xhtml1-lat1;
<!ELEMENT entity ( id, clazz, listfilter?, owner?, auditable, persistent, operations, rowsPerPage?, field+ ) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT clazz (#PCDATA) >

<!ATTLIST entity 
			id CDATA #REQUIRED
		   	clazz CDATA #REQUIRED >

<!ELEMENT listfilter (EMPTY) >
<!ATTLIST listfilter class 		CDATA #REQUIRED>

<!ELEMENT rowsPerPage (#PCDATA) >
<!ELEMENT auditable (#PCDATA) >
<!ELEMENT persistent (#PCDATA) >
<!ELEMENT owner (entity_id , entity_property, local_property?) >

<!ELEMENT entity_id (#PCDATA) >
<!ELEMENT entity_property (#PCDATA) >
<!ELEMENT local_property (#PCDATA) >

<!ELEMENT operations (operation*) >
<!ELEMENT operation (id, enabled?, scope?, visibleIn?, url?, context?, validators?, properties?) >

<!ATTLIST operation 
			id CDATA #REQUIRED
		   	enabled CDATA #IMPLIED
		   	scope CDATA #IMPLIED
		   	visibleIn CDATA #IMPLIED >

<!ELEMENT context ( EMPTY ) >
<!ATTLIST context class 		CDATA #REQUIRED>
<!ELEMENT text (#PCDATA) >
<!ELEMENT icon (#PCDATA) >
<!ELEMENT enabled (#PCDATA) >
<!ELEMENT scope (#PCDATA) > 
<!ELEMENT visibleIn (#PCDATA) >
<!ELEMENT url (#PCDATA) >

<!ELEMENT validators (validator*) >
<!ELEMENT validator (#PCDATA) >

<!ELEMENT field (id, display?, width?, align?, searchCriteria?, multiEditable?, maxLength?, converters?, field-validator*) >

<!ATTLIST operation 
			id CDATA #REQUIRED
		   	display CDATA #IMPLIED
		   	width CDATA #IMPLIED
		   	align CDATA #IMPLIED>

<!ELEMENT display (#PCDATA) >
<!ELEMENT maxLength (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT converters (converter*)>
<!ELEMENT converter (properties?)>
<!ATTLIST converter 
			class 		CDATA #REQUIRED
			operations  CDATA #REQUIRED >
<!ELEMENT field-validator (properties?)>
<!ELEMENT properties (property*)>
<!ELEMENT property ( EMPTY )>
<!ATTLIST property 
      name 		CDATA #REQUIRED
      value 	CDATA #REQUIRED >
<!ELEMENT listfilter (#PCDATA)>
<!ELEMENT showToList (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT searchCriteria (#PCDATA)>
<!ELEMENT multiEditable (#PCDATA)>

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_core/cfg/entities/pmsession.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entity SYSTEM "cfg/entity.dtd">
<entity id="pmsession" clazz="org.jpos.ee.pm.core.PMSession">
    <dataAccess class="org.jpos.ee.pm.ui.DataAccessPMSession" />
    <operations>
        <operation id="list" enabled="true" scope="item" display="all">
            <properties>
                <property name="operation-column-width" value="1px" />
            </properties>
        </operation>
        <operation id="show" enabled="true" scope="item" display="list" />
        <operation id="delete" enabled="true" scope="item" display="show list" confirm="true"/>
    </operations>
    <field id="id" />
    <field id="userid" property="user.username" />
    <field id="username" property="user.name" />
    <field id="lastAccess" />
    <field id="containers" display="show">
        <converters>
            <econverter id="containers-show" />
        </converters>
    </field>
</entity>
