=== jpaoletti/jPOS-Presentation-Manager/modules/pm_core/cfg/monitor.dtd
<!ENTITY % xhtml1-lat1 SYSTEM "xhtml1-lat1.ent">  %xhtml1-lat1;
<!ELEMENT monitor ( id, source, formatter, delay, max ) >
<!ELEMENT id (#PCDATA) >

<!ELEMENT formatter (EMPTY) >
<!ATTLIST formatter class 		CDATA #REQUIRED>

<!ELEMENT source (properties?)>
<!ELEMENT properties (property*)>
<!ELEMENT property ( EMPTY )>
<!ATTLIST property  
    name      CDATA #REQUIRED
    value     CDATA #REQUIRED>
    
<!ELEMENT delay (#PCDATA) >
<!ELEMENT max (#PCDATA) >

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_core/cfg/monitors/q2.xml
<?xml version='1.0' ?>
<!DOCTYPE entity SYSTEM "cfg/monitor.dtd">  
<monitor>
    <id>q2</id>
    <name>Q2 monitor</name>
    <source class="org.jpos.ee.pm.core.monitor.FileMonitorSource" >
        <properties>
            <property name="filename" value="log/q2.log" />
        </properties>
    </source>
    <formatter class="org.jpos.ee.pm.core.monitor.MonitorFormatter" />
    <delay>3000</delay>
    <max>100</max>
</monitor>
