=== jpaoletti/jPOS-Presentation-Manager/modules/cfg/entity.dtd
<!ENTITY % xhtml1-lat1 SYSTEM "xhtml1-lat1.ent">  %xhtml1-lat1;
<!ELEMENT entity ( id, clazz, listfilter?, owner?, auditable, persistent, operations, rowsPerPage?, field+ ) >
<!ELEMENT id (#PCDATA) >
<!ELEMENT clazz (#PCDATA) >

<!ELEMENT listfilter (EMPTY) >
<!ATTLIST listfilter class 		CDATA #REQUIRED>

<!ELEMENT rowsPerPage (#PCDATA) >
<!ELEMENT auditable (#PCDATA) >
<!ELEMENT persistent (#PCDATA) >
<!ELEMENT owner (entity_id , entity_property, local_property?) >

<!ELEMENT entity_id (#PCDATA) >
<!ELEMENT entity_property (#PCDATA) >
<!ELEMENT local_property (#PCDATA) >

<!ELEMENT operations (operation*) >
<!ELEMENT operation (id, text?, icon?, enabled?, scope?, visibleIn?, url?, context?, validators?, properties?) >
<!ELEMENT context ( EMPTY ) >
<!ATTLIST context class 		CDATA #REQUIRED>
<!ELEMENT text (#PCDATA) >
<!ELEMENT icon (#PCDATA) >
<!ELEMENT enabled (#PCDATA) >
<!ELEMENT scope (#PCDATA) > <!-- all, row-->
<!ELEMENT visibleIn (#PCDATA) > <!-- Indicate the operations where the defined operation will be shown -->
<!ELEMENT url (#PCDATA) >

<!ELEMENT validators (validator*) >
<!ELEMENT validator (#PCDATA) >

<!ELEMENT field (id, display?, clazz, width?, align?, sortable?, searchable?, searchCriteria?, multiEditable?, maxLength?, converter?, field-validator*) >
<!ELEMENT display (#PCDATA) > <!--Operations where the field is displayed, could be "all" -->
<!ELEMENT sortable (#PCDATA)>
<!ELEMENT maxLength (#PCDATA)>
<!ELEMENT searchable (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT converter (properties?)>
<!ATTLIST converter class 		CDATA #REQUIRED>
<!ELEMENT field-validator (properties?)>
<!ELEMENT properties (property*)>
<!ELEMENT property ( EMPTY )>
<!ATTLIST property 
      name 		CDATA #REQUIRED
      value 	CDATA #REQUIRED>
<!ELEMENT listfilter (#PCDATA)>
<!ELEMENT showToList (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT searchCriteria (#PCDATA)>
<!ELEMENT multiEditable (#PCDATA)>

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_security_ui/cfg/entities/secusergroup.xml
<?xml version='1.0' ?>
<!DOCTYPE entity SYSTEM "cfg/entity.dtd">  
<entity>
    <id>secusergroup</id>
    <clazz>org.jpos.ee.pm.security.core.PMSecurityUserGroup</clazz>
      <auditable>false</auditable>
      <dataAccess class="org.jpos.ee.pm.security.ui.DataAccessGroup" />
    
    <operations>
        <operation>
            <id>list</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>all</display>
        </operation>        
        <operation>
            <id>add</id>
            <enabled>true</enabled>
            <scope>general</scope>
            <display>list show</display>
        </operation>
        <operation>
            <id>show</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>list</display>
        </operation>
        <operation>
            <id>edit</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>list show</display>
        </operation>
    </operations>
    
    <field>
        <id>name</id>
        <display>all</display>
        <width>200</width>
        <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="add"/>
          </converters>
    </field>
    
    <field>
        <id>description</id>
        <display>all</display>
        <width>200</width>
        <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="add edit"/>
          </converters>
    </field>
    
    <field>
          <id>active</id>
          <display>all</display>
          <width>40</width>
          <align>center</align>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.ShowBooleanConverter" operations="list show">
                   <properties>
                       <property name="true-text" value="Si" />
                       <property name="false-text" value="No" />
                   </properties>
              </converter>
              <converter class="org.jpos.ee.pm.struts.converter.EditBooleanConverter" operations="add edit"/>
          </converters>
      </field>
    
    <field>
        <id>permissions</id>
        <display>all</display>
        <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditCollectionConverter" operations="add edit">
                   <properties>
                    <property name="filter" value="" />
                    <property name="entity" value="secperm" />
                    <property name="collection-class" value="java.util.ArrayList" />
                </properties>
              </converter>
          </converters>
    </field>
</entity>

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_security_ui/cfg/entities/secrule.xml
<?xml version='1.0' ?>
<!DOCTYPE entity SYSTEM "cfg/entity.dtd">  
<entity>
    <id>secrule</id>
    <clazz>org.jpos.ee.pm.security.rules.SECRule</clazz>
      <auditable>true</auditable>
    
    <operations>
        <operation>
            <id>list</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>all</display>
        </operation>        
        <operation>
            <id>show</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>list</display>
        </operation>
        <operation>
            <id>edit</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>list show</display>
        </operation>
    </operations>
    
    <field>
        <id>id</id>
        <display>list show</display>
          <width>60</width>
          <align>center</align>
    </field>
        
    <field>
        <id>description</id>
        <display>list show</display>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.ShowLocalizedStringConverter" operations="list show"/>
          </converters>
    </field>
    
    <field>
          <id>enabled</id>
          <display>all</display>
          <width>40</width>
          <align>center</align>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.ShowBooleanConverter" operations="list show">
                   <properties>
                       <property name="true-text" value="Si" />
                       <property name="false-text" value="No" />
                   </properties>
              </converter>
              <converter class="org.jpos.ee.pm.struts.converter.EditBooleanConverter" operations="edit"/>
          </converters>
      </field>
    <field>
        <id>parameter</id>
        <display>all</display>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="edit"/>
          </converters>
    </field>
    <field>
        <id>applyTo</id>
        <display>list show</display>
          <converters>
              <converter class="org.jpos.ee.pm.security.ui.converter.ShowRuleApplyToConverter" operations="show list"/>
          </converters>
    </field>
    <field>
        <id>updateDate</id>
        <display>show list</display>
    </field>
    <field>
        <id>updateUser</id>
        <display>show</display>
    </field>
</entity>

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_security_ui/cfg/entities/secuserprofile.xml
<?xml version='1.0' ?>
<!DOCTYPE entity SYSTEM "cfg/entity.dtd">  
<entity>
    <id>secuserprofile</id>
      <clazz>org.jpos.ee.pm.security.SECUser</clazz>
      <auditable>true</auditable>
      <dataAccess class="org.jpos.ee.pm.security.ui.DataAccessUser" />
      
      <operations>
          <operation>
              <id>show</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>edit changepassword</display>
          </operation>
          <operation>
              <id>edit</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>show</display>
          </operation>
          <operation>
              <id>changepassword</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>edit show</display>
          </operation>
      </operations>

      <field>
          <id>username</id>
          <width>100</width>
          <display>all</display>
      </field>
      <field>
          <id>name</id>
          <display>all</display>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="edit"/>
          </converters>
      </field>
    <field>
        <id>password</id>
        <display></display>
        <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditPasswordConverter" operations="edit"/>
          </converters>
    </field>
      <field>
          <id>email</id>
          <display>all</display>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="edit"/>
          </converters>
      </field>
</entity>

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_security_ui/cfg/entities/secuser.xml
<?xml version='1.0' ?>
<!DOCTYPE entity SYSTEM "cfg/entity.dtd">  
<entity>
    <id>secuser</id>
      <clazz>org.jpos.ee.pm.security.core.PMSecurityUser</clazz>
      <auditable>false</auditable>
      <dataAccess class="org.jpos.ee.pm.security.ui.DataAccessUser" />
      
      <operations>
          <operation>
              <id>list</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>all</display>
          </operation>
          <operation>
              <id>add</id>
              <enabled>true</enabled>
              <scope>general</scope>
              <display>list</display>
          </operation>
          <operation>
              <id>show</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>list edit</display>
          </operation>
          <operation>
              <id>edit</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>list show</display>
          </operation>
          <operation>
              <id>delete</id>
              <enabled>true</enabled>
              <scope>item</scope>
              <display>list</display>
          </operation>          
      </operations>

      <field>
          <id>username</id>
          <display>all</display>
          <width>100</width>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="add"/>
          </converters>
      </field>
      <field>
          <id>name</id>
          <display>list add show</display>
          <width>200</width>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="add" />
          </converters>
      </field>
      <field>
          <id>active</id>
          <display>all</display>
          <width>40</width>
          <align>center</align>
          <converters>
              <converter class="org.jpos.ee.pm.converter.ShowBooleanConverter" operations="list show">
                   <properties>
                       <property name="true-text" value="Si" />
                       <property name="false-text" value="No" />
                   </properties>
              </converter>
              <converter class="org.jpos.ee.pm.struts.converter.EditBooleanConverter" operations="add edit"/>
          </converters>
      </field>
    <field>
        <id>password</id>
        <display>add</display>
        <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditPasswordConverter" operations="add"/>
          </converters>
    </field>

      <field>
          <id>email</id>
          <display>all</display>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditStringConverter" operations="add edit"/>
          </converters>
      </field>
    
    <field>
        <id>groups</id>
        <display>show add edit list</display>
          <converters>
              <converter class="org.jpos.ee.pm.struts.converter.EditCollectionConverter" operations="add edit">
                <properties>
                    <property name="filter" value="" />
                    <property name="entity" value="secusergroup" />
                    <property name="collection-class" value="java.util.ArrayList" />
                </properties>
              </converter>
          </converters>
    </field>
</entity>

=== jpaoletti/jPOS-Presentation-Manager/modules/pm_security_ui/cfg/entities/secperm.xml
<?xml version='1.0' ?>
<!DOCTYPE entity SYSTEM "cfg/entity.dtd">  
<entity>
    <id>secperm</id>
    <clazz>org.jpos.ee.pm.security.core.PMSecurityPermission</clazz>
      <auditable>false</auditable>
      <dataAccess class="org.jpos.ee.pm.security.ui.DataAccessPerm" />
    
    <operations>
        <operation>
            <id>list</id>
            <enabled>true</enabled>
            <scope>item</scope>
            <display>all</display>
        </operation>        
    </operations>
    
    <field>
        <id>name</id>
        <width>200</width>
        <display>show list</display>
    </field>
    
    <field>
        <id>description</id>
        <display>all</display>
    </field>
</entity>
